name: CI/CD - ECS Blue-Green Deployment

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  APP_NAME: sampleecsapp
  ECR_REPOSITORY: sampleecsapp
  TF_VERSION: 1.6.6

jobs:
  deploy:
    name: Build, Push, Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      run: |
        docker build -t $APP_NAME .
        docker tag $APP_NAME:latest ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest
        docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
